version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    pre-build:
        commands:
            - echo nothing for pre build
    build:
        commands:
            - echo build with maven
            - mvn clean install
    post-build:
        commands:
            - echo build completed
    artifacts:
        files:
            - target/mate.jar
