version: '3.1'

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: mate-user
      MONGO_INITDB_ROOT_PASSWORD: team2pass*J

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081

    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mate-user
      ME_CONFIG_MONGODB_ADMINPASSWORD: team2pass*J
      ME_CONFIG_MONGODB_URL: mongodb://mate-user:team2pass*J@mongo:27017/



